# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 409365b56039bc773fd6b9355b4eeae3785c1ed153036a70b43eda7ddab6ae3602a4bfd49df755e564ac69485c6aaec9474b777c5d5cc206eb2b03e3a52698bc

test:
  secret_key_base: d53b3ce711d319a3b1d25d625a37cde1d776b9c596e694ac36c4795fc9dd832566c531e09f9b0ab2da05248fc97a4cac186a5aff1612ba5336e8cd2984e071ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
